name: roshan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  easy_localization: ^3.0.8
  google_fonts: ^6.3.2
  country_picker: ^2.0.27
  phone_form_field: ^10.0.11+13
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.9.3
  glow_bottom_app_bar: ^1.5.2
  pin_code_text_field: ^1.8.0
  pin_code_fields: ^8.0.1
  story_view: ^0.16.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Almarai
      fonts:
         - asset: custom_fonts/fonts/Almarai-Bold.ttf
#         - asset: fonts/JosefinSans-Bold.ttf

    - family: Roboto
      fonts:
         - asset: custom_fonts/fonts/Roboto-Bold.ttf

    - family: JosefinSans
      fonts:
        - asset: custom_fonts/fonts/JosefinSans-Bold.ttf

    - family: NotoSansArabic
      fonts:
        - asset: custom_fonts/fonts/NotoSansArabic.ttf

# NotoSansArabic-VariableFont_wdth,wght